version: "3.4"

services:
    api:
        build:
            context: .
            target: development
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
        networks:
            - simple-network
        command: npm run dev
    postgres:
        image: postgres
        ports:
            - 6543:6543
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        networks:
            - simple-network
networks:
    simple-network:
        driver: bridge
